import { Inter } from 'next/font/google'
import './globals.css'
import { getServerSession} from 'next-auth'
import Logout from './logout'
import Login from './login'
import Link from 'next/link'
const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({ 
  children,
}) {

  const session = await getServerSession();

  return (
    <html lang="en">
      <body className={inter.className}>
        <nav>
          {!!session && 
          <Logout/>
          }
          {!session && 
          <Login/>
          }
        </nav>
        {children}
        </body>
    </html>
  )
}